import type { MenuItem } from '../../types/menu';

// 前端内置公共菜单
// 未登录可见：公共工具
// 登录后：后端返回为准；此处作为兜底
export const builtInAsideMenus: MenuItem[] = [
  { name: '导航列表', path: '/app/navigation', i18nKey: 'menu.navigation' },
  { name: '象棋·镜', path: '/chess-mirror', i18nKey: 'menu.chessMirror' },
  { name: '文本对比', path: '/v-app/text-difference', i18nKey: 'menu.textDiff' },
  { name: 'JSON 工具', path: '/v-app/json-viewer', i18nKey: 'menu.jsonTool' },
  { name: 'Curl Converter', path: '/tools/curlconverter' },
  { name: '博客', path: 'https://blog.acckm.com', external: true, i18nKey: 'menu.blog' },
  { name: 'PDF 编辑器', path: 'https://pdf.acckm.com', external: true, i18nKey: 'menu.pdfEditor' },
  // 业务菜单仅为兜底；实际显示以后端返回为准
  { name: '一起看', path: '/app/watch-together', i18nKey: 'menu.watchTogether' },
  {
    name: '账号保险库',
    path: '/app/account-vault',
    requiresAuth: true,
    i18nKey: 'menu.accountVault',
  },
  {
    name: '文件管理',
    path: '/app/file-manager',
    requiresAuth: true,
    adminOnly: true,
    i18nKey: 'menu.fileManager',
  },
  { name: '数据库管控', path: '/v-react/db-ops', requiresAuth: true, i18nKey: 'menu.databaseOps' },
  { name: '语音助手', path: '/v-react/assistants', requiresAuth: true, i18nKey: 'menu.assistants' },
  { name: '知识库', path: '/v-react/knowledge-bases', requiresAuth: true, i18nKey: 'menu.knowledgeBases' },
  {
    name: 'AI 模型配置',
    path: '/v-react/ai-admin',
    requiresAuth: true,
    adminOnly: true,
    i18nKey: 'menu.aiAdmin',
  },
  {
    name: '模型调试',
    path: '/v-react/model-playground',
    requiresAuth: true,
    adminOnly: true,
    i18nKey: 'menu.modelPlayground',
  },
  {
    name: '菜单管理',
    path: '/app/menu-admin',
    requiresAuth: true,
    adminOnly: true,
    i18nKey: 'menu.menuAdmin',
  },
  {
    name: '角色管理',
    path: '/app/role-admin',
    requiresAuth: true,
    adminOnly: true,
    i18nKey: 'menu.roleAdmin',
  },
  {
    name: '权限管理',
    path: '/app/permission-admin',
    requiresAuth: true,
    adminOnly: true,
    i18nKey: 'menu.permissionAdmin',
  },
  {
    name: '用户管理',
    path: '/app/user-admin',
    requiresAuth: true,
    adminOnly: true,
    i18nKey: 'menu.userAdmin',
  },
  {
    name: '配置中心',
    path: '/app/config-center',
    requiresAuth: true,
    adminOnly: true,
    i18nKey: 'menu.configCenter',
  },
  {
    name: '博客工作台',
    path: '/app/blog-studio',
    requiresAuth: true,
    adminOnly: true,
    i18nKey: 'menu.blogStudio',
  },
  {
    name: '身份与安全',
    path: '/app/security-center',
    requiresAuth: true,
    i18nKey: 'menu.securityCenter',
  },
  {
    name: 'Agent 平台',
    path: '/app/agent-platform',
    requiresAuth: true,
    adminOnly: true,
    i18nKey: 'menu.agentPlatform',
  },
  { name: 'Obsidian 笔记', path: '/v-react/notes', requiresAuth: true, i18nKey: 'menu.notes' },
  { name: '定时轮询保活', path: '/v-react/keepalive', requiresAuth: true, i18nKey: 'menu.keepalive' },
  { name: '支付', path: '/v-app/payment', requiresAuth: true, i18nKey: 'menu.payment' },
  { name: '待办', path: '/v-app/todo', requiresAuth: true, i18nKey: 'menu.todo' },
];
